# Generated by Django 4.2.1 on 2023-05-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/settings')),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Malls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brands', models.ManyToManyField(related_name='malls', to='core.brands')),
            ],
            options={
                'verbose_name_plural': 'Malls',
            },
        ),
        migrations.CreateModel(
            name='CustomerRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age', models.CharField(choices=[('12-18', '12-18'), ('18-25', '18-25'), ('25-35', '25-35'), ('more-than-35', 'More than 35')], max_length=20)),
                ('mobile_number', models.CharField(max_length=15)),
                ('comments', models.TextField(max_length=1600)),
                ('malls', models.ManyToManyField(related_name='customers', to='core.malls')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
