# Generated by Django 4.2.1 on 2023-05-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecords',
            name='brands',
            field=models.ManyToManyField(related_name='customers', to='core.brands'),
        ),
    ]
