# Generated by Django 4.2.1 on 2023-06-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customerrecords_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecords',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
