# Generated by Django 4.2.1 on 2023-06-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customerrecords_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecords',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
