# Generated by Django 4.2.1 on 2023-06-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customergenderchart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerGenderChart',
        ),
    ]
